// Server-side read layer for /argos-jonli. The registry base is a committed
// JSON (regenerated by scripts/make-argos-base.py); the ARGOS tree comes from
// the store, pushed by the user's browser. Never throws: with no tree yet the
// page renders an empty state.

import raw from "@/data/argos-live-base.json";
import {
  changedSince,
  compute,
  type BaseFile,
  type LiveResult,
  type TreeSnapshot,
} from "./argos-live";
import { getLiveManifest, getLivePrevTree, getLiveTree, type LiveManifest } from "./store";

export const BASE = raw as unknown as BaseFile;

export interface LiveData {
  tree: TreeSnapshot;
  result: LiveResult;
  manifest: LiveManifest | null;
  prevAt: string | null;
  changes: ReturnType<typeof changedSince>;
}

export async function getLive(): Promise<LiveData | null> {
  const [tree, manifest] = await Promise.all([getLiveTree(), getLiveManifest()]);
  if (!tree) return null;
  const prev = await getLivePrevTree();
  return {
    tree,
    manifest,
    result: compute(BASE.orgs, tree),
    prevAt: prev?.at ?? null,
    changes: prev ? changedSince(BASE.orgs, prev, tree) : [],
  };
}
