// Server-side read layer for /argos-jonli. The registry base is a committed
// JSON (regenerated by scripts/make-argos-base.py); the ARGOS tree comes from
// the store, pushed by the user's browser. Never throws: with no tree yet the
// page renders an empty state.

import raw from "@/data/argos-live-base.json";
import {
  changedSince,
  compute,
  type BaseFile,
  type LiveResult,
  type TreeSnapshot,
} from "./argos-live";
import { resolveOwnStir, type OwnStirApplied, type OwnStirPending } from "./argos-match";
import { getLiveManifest, getLivePrevTree, getLiveTree, getStirAssign, type LiveManifest } from "./store";

export const BASE = raw as unknown as BaseFile;

export interface LiveData {
  tree: TreeSnapshot;
  result: LiveResult;
  manifest: LiveManifest | null;
  prevAt: string | null;
  changes: ReturnType<typeof changedSince>;
  /** STIRs found in the tree for STIR-less registry rows: applied, and waiting for a person. */
  own: { applied: OwnStirApplied[]; pending: OwnStirPending[] };
}

export async function getLive(): Promise<LiveData | null> {
  const [tree, manifest] = await Promise.all([getLiveTree(), getLiveManifest()]);
  if (!tree) return null;
  const [prev, stored] = await Promise.all([getLivePrevTree(), getStirAssign()]);
  // Strong matches are applied here too, so a page never waits for the next tree to show them;
  // POST /api/argos-tree stores them.
  const own = resolveOwnStir(BASE.orgs, BASE.ignoreStir ?? [], tree.rows, stored, tree.at);
  return {
    tree,
    manifest,
    result: compute(own.orgs, tree, BASE.ignoreStir),
    prevAt: prev?.at ?? null,
    changes: prev ? changedSince(own.orgs, prev, tree) : [],
    own: { applied: own.applied, pending: own.pending },
  };
}
